language: cpp
cache: ccache
os: linux
dist: trusty
sudo: required
services: docker
compiler: gcc
install:
- docker build .travis -t atomify
script:
- docker run -v $(pwd):/app -t atomify bash .travis/ubuntu.sh
after_success:
- openssl aes-256-cbc -K $encrypted_082f9a3f227a_key -iv $encrypted_082f9a3f227a_iv
  -in .snapcraft/travis_snapcraft.cfg -out .snapcraft/snapcraft.cfg -d
deploy:
  'on':
    branch: dev
  provider: script
  script: docker run -v $(pwd):/app -t atomify sh -c "cd /app/ && snapcraft && snapcraft push *.snap --release
    edge"
  skip_cleanup: true
