language: cpp
compiler:
  - gcc
sudo: required
services: docker
# before_install:
  # - docker pull ubuntu
script:
  - docker build -t ovilab/atomify-lammps -f docker/atomify-lammps/Dockerfile .
  - mkdir output
  - docker run -v $(pwd)/output:/app/output ovilab/atomify-lammps /bin/sh -c "cp /app/atomify-lammps_*snap /app/output/"
  - ls output
