language: cpp
os:
  - linux
compiler:
  - gcc
sudo: required
dist: trusty
install:
  - sudo add-apt-repository -y ppa:beineri/opt-qt551-trusty
  - sudo apt-get -qq update
  - sudo apt-get -qq install qt55declarative
script:
  - ./configure.py
  - source /opt/qt55/bin/qt55-env.sh
  - /opt/qt55/bin/qmake
  - make
