language: cpp
os:
  - linux
compiler:
  - gcc
sudo: required
dist: trusty
install:
  - sudo add-apt-repository -y ppa:beineri/opt-qt57-trusty
  - sudo apt-get -qq update
  - sudo apt-get -qq install qt573d
  - sudo apt-get -qq install qt57charts-no-lgpl
  - sudo apt-get -qq install qt57datavis-no-lgpl
  - sudo apt-get -qq install qt57declarative
  - sudo apt-get -qq install qt57svg
script:
  - ./configure.py
  - source /opt/qt57/bin/qt57-env.sh
  - /opt/qt57/bin/qmake
  - make
