language: cpp
os:
  - linux
branches:
  only:
    - master
compiler:
  - gcc
  - clang
sudo: required
dist: trusty
addons:
  apt:
    sources:
      - ubuntu-sdk-team
      - beineri/opt-qt551-trusty
    packages:
      - qtdeclarative5-dev
script:
  - ./configure.py
  - /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
  - make
