language: cpp
compiler:
- gcc
sudo: required
services: docker
script:
- docker build -t ovilab/atomify-lammps -f .docker/atomify-lammps/Dockerfile .
- mkdir output
- docker run -v $(pwd)/output:/app/output ovilab/atomify-lammps /bin/sh -c "cp /app/atomify-lammps_*snap /app/output/atomify-lammps.snap"
- ls output
notifications:
  slack:
    on_success: change
    on_failure: always
    secure: XWZ6IEeCqMrnEqf1jqgS6j2XFC0qsIDsNmI+aJfIBhLcG+Zo7pbEdownrnSLa4P2UxgBWN1YepQbAegOZavleF7/+eBKBAuxKx3tTyCtsaAWsvPHhuxryg8VNnRNzHzQVTqDzJfekTw/9yNDGYPtzxtD0e+8jwAHqLdFdtEFHRc=
deploy:
  provider: releases
  api_key:
    secure: zArZaaHe6ICyfZLsWG610NxLlnquL+66D+J2GaYwS+BQqgpLzfpuKxZeFMidt5IfODct+nf5qzVcWnxMFTD3Baaeqsfua7FYL+6ZPcJTX9g/qFMNhXRQyl2FCl9ykNkM0rBz2BddhezC4c4cZkzwlBkvR7NcvmbMqJxKAeGMUVg=
  file: output/atomify-lammps.snap
  on:
    repo: ComputationalPhysics/atomify-lammps
    branch: dev
  skip_cleanup: true
