language: cpp
compiler:
- gcc
sudo: required
services: docker
script:
- docker run -v $(pwd):$(pwd) ubuntu /bin/sh -c "apt-get -qq update; apt-get install
  -qq sudo; cd $(pwd); ./build.sh"
- ls -la
notifications:
  slack:
    secure: XWZ6IEeCqMrnEqf1jqgS6j2XFC0qsIDsNmI+aJfIBhLcG+Zo7pbEdownrnSLa4P2UxgBWN1YepQbAegOZavleF7/+eBKBAuxKx3tTyCtsaAWsvPHhuxryg8VNnRNzHzQVTqDzJfekTw/9yNDGYPtzxtD0e+8jwAHqLdFdtEFHRc=
