name: atomify
version: "2.0.5"
summary: Atomify LAMMPS
description: Editor for the molecular dynamics simulator LAMMPS
confinement: strict
grade: stable

apps:
  atomify:
    command: desktop-launch custom-qt-helper atomify
    plugs: ['unity7', 'x11', 'opengl', 'network', 'network-bind', 'home']

parts:
  move:
    plugin: dump
    source: snapdump
    stage:
      - bin
      - lib
      - plugins
      - qml
  conf:
    plugin: dump
    source: .snapcraftm
    stage:
      - bin
  helpers:
    plugin: nil
    after:
      - move # NOTE move and conf must be here due install error for desktop-qt5 otherwise
      - conf
      - desktop-qt5
  
